const SELECT_USER_BY_ID = `
  SELECT * FROM USER WHERE id = ?
`;

const INSERT_AUDIO = `
  INSERT INTO AUDIO SET ?
`;

const INSERT_HISTORY = `
  INSERT INTO HISTORY SET ?
`;

const SELECT_HISTORY_BY_USER_ID = `
  SELECT * FROM HISTORY WHERE user_id = ? ORDER BY id ASC
`;

const SELECT_HISTORY_USER_ID_AND_CONTINUE = `
  SELECT * FROM HISTORY WHERE user_id = ? AND isCompleted is FALSE ORDER BY id ASC
`;

const SELECT_HISTORY_USER_ID_AND_COMPLETE = `
  SELECT * FROM HISTORY WHERE user_id = ? AND isCompleted is TRUE ORDER BY id ASC
`;

const SELECT_AUDIO_BY_USER_ID = `
  SELECT * FROM AUDIO WHERE user_id = ? is TRUE ORDER BY id ASC
`;

module.exports.SELECT_USER_BY_ID = SELECT_USER_BY_ID;
module.exports.INSERT_AUDIO = INSERT_AUDIO;
module.exports.INSERT_HISTORY = INSERT_HISTORY;
module.exports.SELECT_HISTORY_BY_USER_ID = SELECT_HISTORY_BY_USER_ID;
module.exports.SELECT_HISTORY_USER_ID_AND_CONTINUE = SELECT_HISTORY_USER_ID_AND_CONTINUE;
module.exports.SELECT_HISTORY_USER_ID_AND_COMPLETE = SELECT_HISTORY_USER_ID_AND_COMPLETE;
module.exports.SELECT_AUDIO_BY_USER_ID = SELECT_AUDIO_BY_USER_ID;
